[package]
name = "range_bounds_map"
version = "0.0.4"
authors = ["James Forster <james.forsterer@gmail.com>"]
edition = "2021"
description = """
This crate provides `RangeBoundsMap` and `RangeBoundsSet`
"""
documentation = "https://docs.rs/range_bounds_map"
readme = "README.md"
homepage = "https://github.com/ripytide/range_bounds_map"
repository = "https://github.com/ripytide/range_bounds_map"
license = "AGPL-3.0-or-later"
keywords = ["data-structures", "map", "data", "library"]
categories = ["data-structures"]

[dependencies]
either = "1.8.0"
serde = {version = "1.0.148", features = ["derive"]}
itertools = "0.10.5"
labels = "0.0.2"
pretty_assertions = "1.3.0"

[dev-dependencies]
ordered-float = "3.4.0"
