[package]
name = "range_bounds_map"
version = "0.0.1"
authors = ["James Forster"]
edition = "2021"
description = """
This crate provides `RangeBoundsMap` and `RangeBoundsSet`.

`RangeBoundsMap` is similar to `BTreeMap` except `RangeBoundsMap`
uses any type that implements the `RangeBounds` trait as keys, while
maintaining two invariants:
- No two keys may overlap
- A keys' `start_bound()` <= its `end_bound()`

`RangeBoundsSet` is like `RangeBoundsMap` except it
uses `()` as values, as `BTreeSet` does for `BTreeMap`
"""
documentation = "https://docs.rs/range_bounds_map"
readme = "README.md"
homepage = "https://github.com/ripytide/range_bounds_map"
repository = "https://github.com/ripytide/range_bounds_map"
license = "GPL-3.0-or-later"
keywords = ["data-structures", "map", "data", "library"]
categories = ["data-structures"]

[dependencies]
either = "1.8.0"
serde = {version = "1.0.148", features = ["derive"]}
itertools = "0.10.5"
labels = {path = "../robot_sweet_shop/labels"}
pretty_assertions = "1.3.0"

[dev-dependencies]
ordered-float = "3.4.0"
