[package]
name = "range_bounds_map"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.8.0"

[dev-dependencies]
ordered-float = "3.4.0"
