# todo this file put back to normal

# - rename crate too
# - add link to previous crate on readme
# - update shared descriptions to note the discreteness
# - fix doc.rs links in docs to print at new crate name
# - fix doc warnings
hard_tabs=true
imports_granularity="Module"
group_imports="StdExternalCrate"
