# todo put back to normal
# - rename RangeBounds{Set,Map} to DiscreteRange{Set,Map}
# - rename crate too
# - add link to previous crate on readme
# - update shared descriptions to note the discreteness
hard_tabs=true
imports_granularity="Module"
group_imports="StdExternalCrate"
