[package]
name = "range_bounds_set"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.8.0"

[dev-dependencies]
color-backtrace = "0.5.1"
ranges = "0.3.3"
